In [2]:
import pandas as pd
import numpy as np

# Parte 1 - NumPy

In [ ]:
# 1. ✅
array1 = np.arange(10, 50)
#En la posición 0 esta el número 10 y en la posición el último número (49)

array1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
# 2. ❌
array2 = array1

#Tendra en la posición 0 el 49 y en la -1 el 10

<function ndarray.transpose>

In [ ]:
# 3. ✅
array3 = np.arange(0, 9).reshape(3, 3)

array3.shape

# Con [0, :] mostramos la primera fila
# Con [:, 0] mostramos la primera columna

array([0, 3, 6])

In [61]:
#4. ❌
array4 = np.random.rand(3, 3, 3)
array4

# (3, 3, 3)
# Primer parametro filas, segundo columnas y tercero "capas"


array([[[0.79094688, 0.24828903, 0.19916327],
        [0.82633465, 0.30770421, 0.22019355],
        [0.9705657 , 0.45389803, 0.82857458]],

       [[0.68574477, 0.06554858, 0.43793181],
        [0.88284785, 0.47974489, 0.39598393],
        [0.53956443, 0.56067519, 0.6976605 ]],

       [[0.27336435, 0.55284111, 0.35642874],
        [0.15814328, 0.54564658, 0.56122012],
        [0.39157022, 0.82278984, 0.98484435]]])

In [ ]:
# 5. ❌

array5 = np.full((10, 10), 0)
array5

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
# 6. ❌

# Con [0, :] mostramos la primera fila
# Con [:, 0] mostramos la primera columna

array6 = np.arange(20).reshape(5, 4)

array6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:

for i in range(4):
    print(array6[:, i].max())
    print(array6[:, i].min())
    print(array6[i, :].max())
    print(array6[i, :].min())

print(array6.max())
print(array6.min())

print(array6.max(axis=0))
print(array6.min(axis=0))
print(np.max(array6))

# np.max(matriz) muestra el valor maximo de esa matriz 
# y matriz.max(axis=0) muestra la fila donde se encuentra ese valor




16
0
3
0
17
1
7
4
18
2
11
8
19
3
15
12
19
0
[16 17 18 19]
[0 1 2 3]
19


In [ ]:
print(array6[:, 0].max())
print(array6[:, 1].max())
print(array6[:, 2].max())
print(array6[:, 3].max())

# Parte 2 - Pandas básico